# Generated by Django 5.2 on 2025-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rater',
            old_name='num_starts',
            new_name='num_stars',
        ),
    ]
